aws_region         = "us-east-1"
project_name       = "ecommerce-skilltest"
instance_type      = "t3.micro"
key_name           = "hv_skilltest_3"
ssh_cidr           = "0.0.0.0/0"
dockerhub_username = "bsskalyan"
image_tag          = "latest"
